# Generated by Django 4.1.4 on 2023-01-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_isverified_user_otp_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
    ]
